In [14]:
import numpy as np


In [15]:
a = np.array ([1,3,5,7,9,11])
print (a)

[ 1  3  5  7  9 11]


In [16]:
a = np.arange (1,12,2)
print(a)

[ 1  3  5  7  9 11]


In [17]:
a = np.linspace(5, 8, 13) 
print(a)

[5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75 8.  ]


In [18]:
a = np.zeros((4, 3), dtype = np.int16)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
a = np.ones ((2 , 3), dtype = np.int16)
print(a)

[[1 1 1]
 [1 1 1]]


In [20]:
a = np.full((6,), 88)
print(a)

[88 88 88 88 88 88]


In [21]:
a = np.fromstring('25 30 35 40' , dtype = np.int, sep=' ')
print(a)

[25 30 35 40]


In [24]:
a = np.array([[1, 3, 5],[7 ,9 , 11]])
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [23]:
b = np.zeros_like(a)
print(b)


[[0 0 0]
 [0 0 0]]
